/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.yash.addressbook.gui;

import com.yash.addressbook.model.User;
import com.yash.addressbook.service.UserService;
import com.yash.addressbook.serviceimpl.UserServiceImpl;

/**
 *
 * @author aashay.sharma
 */
public class UserUpdateForm extends javax.swing.JFrame {

    /**
     * Creates new form UserUpdateForm
     */
    private UserService userService = new UserServiceImpl();
    private User user;
    
    public UserUpdateForm(int id) {
        initComponents();
        user = new User();
        user = userService.getUser(id);
        userName.setText(user.getUserName());
        userPhone.setText(user.getPhoneNo());
        userAddress.setText(user.getAddress());
        userEmail.setText(user.getEmail());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        userPhone = new javax.swing.JTextField();
        userAddress = new javax.swing.JTextField();
        userEmail = new javax.swing.JTextField();
        userName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel1.setText("phone");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(94, 126, 88, 37);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel2.setText("Address");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(94, 179, 88, 37);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel3.setText("Email");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(94, 232, 88, 37);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel5.setText("Username");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(94, 73, 88, 37);
        jPanel1.add(userPhone);
        userPhone.setBounds(200, 129, 224, 32);
        jPanel1.add(userAddress);
        userAddress.setBounds(200, 182, 224, 32);
        jPanel1.add(userEmail);
        userEmail.setBounds(197, 235, 224, 32);

        userName.setEditable(false);
        jPanel1.add(userName);
        userName.setBounds(197, 76, 227, 32);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 2, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("User Form");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(103, 16, 308, 48);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(132, 285, 94, 42);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\aashay.sharma\\Downloads\\back-button (2).png")); // NOI18N
        jLabel4.setText("Back");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(15, 23, 79, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\aashay.sharma\\Pictures\\background1.jpg")); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 440, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        user.setUserName(userName.getText());
        user.setAddress(userAddress.getText());
        user.setPhoneNo(userPhone.getText());
        user.setEmail(userEmail.getText());
        System.out.println(user.getPassword());
        userService.update(user);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField userAddress;
    private javax.swing.JTextField userEmail;
    private javax.swing.JTextField userName;
    private javax.swing.JTextField userPhone;
    // End of variables declaration//GEN-END:variables
}
